[package]
name = "qrlyzer"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "qrlyzer"
crate-type = ["cdylib"]

[dependencies]
image = "0.25.5"
imageproc = "0.25.0"
pyo3 = "0.23.3"
rqrr = "0.9.0"
rxing = "0.7.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
