name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Test Rust library
        run: cargo test
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Create and start virtual environment
        run: |
          python3 -m venv .venv
          source venv/bin/activate
      - name: Install Python dependencies
        run: pip install maturin pytest Pillow
      - name: Build and install Python wheel
        run: maturin develop
      - name: Test Python wheel
        run: pytest -v .
